import React, { useState, useEffect, useRef } from 'react';
import { supabase } from '../supabaseClient';
import { DmgHealRow } from './PlayerCard';
import { getUnifiedResourceConfig, readBooleanField, readNumberField, getClassEntries } from '../utils/classResources';

const CONDITIONS = [ { code:'BLD', colour:'#6b5b95' }, { code:'CHM', colour:'#e8a0bf' }, { code:'DEF', colour:'#888' }, { code:'FRG', colour:'#9b2335' }, { code:'GRP', colour:'#8b6914' }, { code:'INC', colour:'#b5451b' }, { code:'INV', colour:'#4a4a7a' }, { code:'PAR', colour:'#7a4a9a' }, { code:'PET', colour:'#888' }, { code:'PSN', colour:'#3a7a3a' }, { code:'PRN', colour:'#7a6030' }, { code:'RST', colour:'#8b4513' }, { code:'STN', colour:'#4a4a7a' }, { code:'UNC', colour:'#2a2a3a' }, { code:'EXH', colour:'#5a3a7a' }, { code:'HEX', colour:'#6a0dad' } ];
const CONDITION_COLOURS = Object.fromEntries(CONDITIONS.map(c => [c.code, c.colour]));
const DAMAGE_TYPES = ['acid','bludgeoning','cold','fire','force','lightning','necrotic','piercing','poison','psychic','radiant','slashing','thunder'];
const MODS = ['str','dex','con','int','wis','cha'];
function getCombatantInitiativeMod(combatant, playerStates) { if (combatant.side === 'PC') { const state = playerStates.find(s => s.combatant_id === combatant.id); return state?.profiles_players?.initiative_mod ?? combatant.initiative_mod ?? 0; } return combatant.initiative_mod ?? 0; }
function sortCombatants(combatants, playerStates = []) { return [...combatants].sort((a,b)=>{ const ai=a.initiative_total ?? -999; const bi=b.initiative_total ?? -999; if (bi!==ai) return bi-ai; const am=getCombatantInitiativeMod(a, playerStates); const bm=getCombatantInitiativeMod(b, playerStates); if (bm!==am) return bm-am; return a.id < b.id ? -1 : 1; }); }
export function getDisplayOrderedCombatants(combatants, turnIndex) { if (!combatants.length) return []; const safeIndex=Math.max(0, Math.min(turnIndex ?? 0, combatants.length-1)); return [...combatants.slice(safeIndex), ...combatants.slice(0,safeIndex)]; }
function nextZeroHpConditions(newHp, conditions = []) { const next=[...conditions]; if (newHp===0) { if (!next.includes('UNC')) next.push('UNC'); if (!next.includes('PRN')) next.push('PRN'); return next; } if (newHp>0) return next.filter(c=>c!=='UNC'); return next; }
function compactObject(obj){ return Object.fromEntries(Object.entries(obj).filter(([,v])=>v!==undefined)); }
function formatSingleClassEntry(entry){ if(!entry) return ''; const classPart=[entry.displayClass, entry.subclassName].filter(Boolean).join(' • '); const levelPart=entry.level ? `Level ${entry.level}` : ''; return [classPart, levelPart].filter(Boolean).join(' • '); }
function formatClassLine(source = {}) { return getClassEntries(source).map(formatSingleClassEntry).filter(Boolean).join(' / '); }
function getResourceConfig(profile = {}, state = {}) { return getUnifiedResourceConfig(profile, state, { compactLabels: true, includeHitDice: true, includeWarlockSlots: false, includeNaturalRecovery: false }).filter(r => r.id !== 'warlock-slots'); }
function resolveResourceCounts(resource, state) { const rawCurrent = readNumberField(state, [resource.currentKey], null); const rawMax = readNumberField(state, [resource.maxKey], null); const fallbackCurrent = resource.fallbackCurrent ?? 0; const fallbackMax = resource.fallbackMax ?? 0; if ((rawCurrent === null && rawMax === null) || ((rawCurrent ?? 0) === 0 && (rawMax ?? 0) === 0 && fallbackMax > 0)) return { current: fallbackCurrent, max: fallbackMax }; return { current: rawCurrent ?? fallbackCurrent, max: rawMax ?? fallbackMax }; }
function MiniHpBar({ current, max, tempHp = 0, color, label }) { const pct=max>0?Math.max(0,Math.min(100,(current/max)*100)):0; const tempPct=max>0?Math.max(0,Math.min(100,(tempHp/max)*100)):0; const barColor=color || (pct>50?'var(--hp-high)':pct>25?'var(--hp-mid)':'var(--hp-low)'); return <div style={{display:'flex',flexDirection:'column',gap:2}}>{label && <span style={{fontSize:9,color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'0.04em'}}>{label}</span>}<div style={{position:'relative',height:6,background:'var(--bg-panel-3)',borderRadius:3,overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,height:'100%',width:`${pct}%`,background:barColor,borderRadius:3,transition:'width 0.3s'}} />{tempHp>0 && <div style={{position:'absolute',right:0,top:0,height:'100%',width:`${Math.min(tempPct,100-pct)}%`,background:'var(--hp-temp)',opacity:0.7,borderRadius:3}} />}</div></div>; }
function PcResourceSummary({ profile, state, isDM, onUpdate }) { const resources = getResourceConfig(profile || {}, state || {}); if(resources.length===0) return null; async function updateResourceFields(updates){ const payload=compactObject(updates); if(!state?.id || Object.keys(payload).length===0) return; await supabase.from('player_encounter_state').update(payload).eq('id', state.id); onUpdate(); } return <div style={{marginTop:6,display:'flex',flexWrap:'wrap',gap:6}}>{resources.map(resource=><PcResourceChip key={resource.id} resource={resource} state={state} isDM={isDM} onUpdateFields={updateResourceFields} />)}</div>; }
function PcResourceChip({ resource, state, isDM, onUpdateFields }) { if(resource.type==='toggle'){ const rawValue=readBooleanField(state,[resource.boolKey],null); const ready=rawValue===null ? !!resource.fallbackReady : (resource.toggleMode==='available' ? !!rawValue : !rawValue); async function toggle(){ if(!isDM) return; const nextReady=!ready; const stored = resource.toggleMode==='available' ? nextReady : !nextReady; await onUpdateFields({[resource.boolKey]: stored}); } return <button type="button" onClick={toggle} disabled={!isDM} style={{display:'inline-flex',alignItems:'center',gap:4,padding:'2px 7px',borderRadius:999,border:`1px solid ${ready?'var(--accent-green)':'var(--accent-red)'}`,background:ready?'rgba(62,207,106,0.08)':'rgba(224,48,80,0.08)',color:ready?'var(--accent-green)':'var(--accent-red)',fontSize:10,fontWeight:700,cursor:isDM?'pointer':'default'}}><span>{resource.label}</span><span>{ready ? (resource.readyLabel || 'Ready') : (resource.spentLabel || 'Used')}</span></button>; }
 const { current, max } = resolveResourceCounts(resource, state); if(resource.type==='counter'){ async function adjust(delta){ if(!isDM) return; const next=Math.max(0,Math.min(max,current+delta)); if(next===current) return; await onUpdateFields({[resource.currentKey]:next,[resource.maxKey]:max}); } return <div style={{display:'inline-flex',alignItems:'center',gap:4,padding:'2px 7px',borderRadius:999,border:'1px solid var(--border)',background:'var(--bg-panel-3)',fontSize:10,fontWeight:700}}><span>{resource.label}</span>{isDM && <button onClick={()=>adjust(-1)} style={{background:'none',border:'none',color:'var(--text-secondary)',cursor:'pointer',padding:0}}>−</button>}<span>{current}/{max}</span>{isDM && <button onClick={()=>adjust(1)} style={{background:'none',border:'none',color:'var(--text-secondary)',cursor:'pointer',padding:0}}>+</button>}</div>; }
 async function setPips(nextCurrent){ if(!isDM) return; const clamped=Math.max(0,Math.min(max,nextCurrent)); await onUpdateFields({[resource.currentKey]:clamped,[resource.maxKey]:max}); } return <div style={{display:'inline-flex',alignItems:'center',gap:4,padding:'2px 7px',borderRadius:999,border:'1px solid var(--border)',background:'var(--bg-panel-3)',fontSize:10,fontWeight:700}}><span>{resource.label}</span><span style={{display:'inline-flex',gap:3}}>{Array.from({length:max}).map((_,i)=>{ const active=i<current; return <button key={i} type="button" onClick={()=>setPips(active?i:i+1)} disabled={!isDM} style={{width:10,height:10,borderRadius:'50%',padding:0,border:`1.5px solid ${active?'var(--accent-blue)':'var(--border-strong)'}`,background:active?'var(--accent-blue)':'transparent',cursor:isDM?'pointer':'default'}} />; })}</span></div>; }

export default function InitiativePanel({ encounter, combatants, playerStates = [], role, onUpdate, myCombatantId = null }) {
  const isDM = role === 'dm'; const isDisplay = role === 'display'; const sortedOriginal = sortCombatants(combatants, playerStates); const activeTurnIndex = encounter?.turn_index ?? 0; const displayOrdered = getDisplayOrderedCombatants(sortedOriginal, activeTurnIndex); const activeCombatantId = sortedOriginal[activeTurnIndex]?.id ?? null;
  return <div className="panel"><div className="panel-title">{isDisplay ? 'Initiative Feed' : 'Initiative Order'}</div><div className="initiative-list">{displayOrdered.map((c, displayIndex)=>{ const playerState = playerStates.find(s=>s.combatant_id===c.id); const originalIndex = sortedOriginal.findIndex(item=>item.id===c.id); const isActive = c.id===activeCombatantId; const isNextUp = displayIndex===1; return <InitiativeRow key={c.id} combatant={c} playerState={playerState} isActive={isActive} isNextUp={isNextUp} isDM={isDM} onUpdate={onUpdate} sorted={sortedOriginal} idx={originalIndex} encounterId={encounter?.id} myCombatantId={myCombatantId} />; })}</div></div>;
}

function InitiativeRow({ combatant, playerState, isActive, isNextUp, isDM, onUpdate, sorted, idx, encounterId, myCombatantId }) {
  const [inputValue, setInputValue] = useState(combatant.initiative_total != null ? String(combatant.initiative_total) : ''); const isFocused = useRef(false); const savingRef = useRef(false);
  useEffect(()=>{ if(!isFocused.current) setInputValue(combatant.initiative_total != null ? String(combatant.initiative_total) : ''); }, [combatant.initiative_total]);
  const isPC = combatant.side==='PC'; const conditions=combatant.conditions || []; const wildshapeActive = !!playerState?.wildshape_active; const pcHpCurrent=wildshapeActive ? (playerState?.wildshape_hp_current ?? 0) : (playerState?.current_hp ?? null); const pcProfileMax=playerState?.profiles_players?.max_hp ?? null; const pcMaxOverride=playerState?.max_hp_override ?? null; const pcHpMax=wildshapeActive ? (playerState?.wildshape_hp_max ?? 1) : (pcMaxOverride !== null ? pcMaxOverride : pcProfileMax); const tempHp=wildshapeActive ? 0 : (playerState?.temp_hp ?? 0); const reactionUsed=playerState?.reaction_used ?? false; const pcConditions=playerState?.conditions || []; const passivePerception=isPC && playerState?.profiles_players ? (10 + (playerState.profiles_players.skill_perception ?? 0)) : null; const wsHpCurrent=playerState?.wildshape_hp_current ?? 0; const wsFormName=playerState?.wildshape_form_name ?? null; const wsHpMax=playerState?.wildshape_hp_max ?? null; const enemyHpCurrent=combatant.hp_current ?? null; const enemyHpMax=combatant.hp_max ?? null; const showPcHp=isPC && pcHpCurrent !== null && pcHpMax !== null; const classLine=isPC ? formatClassLine(playerState?.profiles_players || {}) : formatClassLine(combatant); const ancestryLine=isPC ? (playerState?.profiles_players?.ancestry_name || '') : ''; const miniMarker=combatant.mini_marker || '';
  async function saveInitiative(){ if(savingRef.current) return; const total=parseInt(inputValue,10); if(isNaN(total)) return; savingRef.current=true; await supabase.rpc('set_initiative',{p_combatant_id:combatant.id,p_total:total}); savingRef.current=false; onUpdate(); }
  async function moveUp(){ if(idx<=0) return; const neighbor=sorted[idx-1]; await supabase.rpc('set_initiative',{p_combatant_id:combatant.id,p_total:(neighbor.initiative_total ?? 0)+1}); onUpdate(); }
  async function moveDown(){ if(idx>=sorted.length-1) return; const neighbor=sorted[idx+1]; await supabase.rpc('set_initiative',{p_combatant_id:combatant.id,p_total:Math.max(0,(neighbor.initiative_total ?? 0)-1)}); onUpdate(); }
  async function toggleReaction(){ if(!playerState) return; await supabase.from('player_encounter_state').update({reaction_used:!reactionUsed}).eq('id', playerState.id); onUpdate(); }
  async function applyPcDamage(amount){ if(!playerState || !amount || amount<=0) return; if(wildshapeActive){ const newHp=Math.max(0, wsHpCurrent-amount); await supabase.from('player_encounter_state').update({ wildshape_hp_current:newHp }).eq('id', playerState.id); onUpdate(); return; } const curHp=playerState.current_hp ?? 0; const curTemp=playerState.temp_hp ?? 0; let remaining=amount; const updates={}; if(curTemp>0){ const burn=Math.min(curTemp,remaining); remaining -= burn; updates.temp_hp=curTemp-burn; } if(remaining>0){ const newHp=Math.max(0,curHp-remaining); updates.current_hp=newHp; updates.conditions=nextZeroHpConditions(newHp,pcConditions); } await supabase.from('player_encounter_state').update(updates).eq('id', playerState.id); onUpdate(); }
  async function applyPcHeal(amount){ if(!playerState || !amount || amount<=0) return; if(wildshapeActive){ const newHp=Math.min(wsHpMax ?? 1, wsHpCurrent+amount); await supabase.from('player_encounter_state').update({ wildshape_hp_current:newHp }).eq('id', playerState.id); onUpdate(); return; } const curHp=playerState.current_hp ?? 0; const effectiveMax=pcMaxOverride ?? pcProfileMax ?? 999; const newHp=Math.min(effectiveMax,curHp+amount); await supabase.from('player_encounter_state').update({current_hp:newHp,conditions:nextZeroHpConditions(newHp,pcConditions)}).eq('id', playerState.id); onUpdate(); }
  return <div className={`initiative-row ${isActive?'active-turn':''} ${isNextUp?'initiative-row--next-up':''}`} style={{display:'block',padding:'8px 12px'}}><div style={{display:'flex',alignItems:'stretch',gap:8}}>{isDM && <div style={{display:'flex',flexDirection:'column',gap:1,justifyContent:'center'}}><button style={{fontSize:9,lineHeight:1,padding:'1px 3px'}} onClick={e=>{e.stopPropagation(); moveUp();}}>▲</button><button style={{fontSize:9,lineHeight:1,padding:'1px 3px'}} onClick={e=>{e.stopPropagation(); moveDown();}}>▼</button></div>}{isDM ? <input className="initiative-number-input" type="number" value={inputValue} onChange={e=>setInputValue(e.target.value)} onFocus={()=>{isFocused.current=true;}} onBlur={()=>{isFocused.current=false; saveInitiative();}} /> : <span className="initiative-number">{combatant.initiative_total ?? '—'}</span>}<div style={{flex:1,minWidth:0,display:'flex',flexDirection:'column',gap:6}}><div className="initiative-name-bar"><div className="initiative-name-bar-main">{miniMarker && <span className="initiative-mini-marker">{miniMarker}</span>}<span className="initiative-name-bar-text">{combatant.name}</span></div></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}>{(classLine || ancestryLine) && <div style={{display:'flex',flexDirection:'column',gap:2,minWidth:0,flex:1}}>{classLine && <span style={{fontSize:10,color:'var(--text-secondary)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{classLine}</span>}{ancestryLine && <span style={{fontSize:10,color:'var(--text-muted)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{ancestryLine}</span>}</div>}{isPC && <button className={`reaction-pill ${reactionUsed?'reaction-pill--used':'reaction-pill--ready'}`} onClick={e=>{e.stopPropagation(); toggleReaction();}}>⚡ {reactionUsed?'USED':'REACT'}</button>}</div></div></div>{showPcHp && <div style={{marginTop:6,display:'flex',flexDirection:'column',gap:4}}>{wildshapeActive && wsHpMax != null && <MiniHpBar current={wsHpCurrent} max={wsHpMax} color="var(--accent-green)" label={wsFormName ? `🐻 ${wsFormName}` : '🐻 Beast Form'} />}{!wildshapeActive && <MiniHpBar current={pcHpCurrent} max={pcHpMax} tempHp={tempHp} />}</div>}{isPC && <PcResourceSummary profile={playerState?.profiles_players || {}} state={playerState || {}} isDM={isDM} onUpdate={onUpdate} />}{isPC && passivePerception !== null && <div style={{marginTop:4,fontSize:10,color:'var(--text-muted)'}}>PP {passivePerception}</div>}{isPC && conditions.length>0 && <div style={{marginTop:4,display:'flex',flexWrap:'wrap',gap:4}}>{conditions.map(code=><span key={code} className="condition-chip" style={{background:CONDITION_COLOURS[code] || 'var(--cond-default)'}}>{code}</span>)}</div>}{isPC && <div style={{marginTop:6}}><DmgHealRow onDamage={applyPcDamage} onHeal={applyPcHeal} compact /></div>}</div>;
}
